### PR TITLE
4th Win wxWidgets 3.1.2 & opencpn.lib for 4.99mui

### PR DESCRIPTION
**Pull request by rgleason**

### CODE REVIEW

**Comment by nohal** [comment]
DELETE LINE 36 FROM `appveyor.yml`

**Comment by rgleason** [comment]
> CMake Error: The source directory "C:/project" does not appear to contain CMakeLists.txt.
> Specify --help for usage, or press the help button on the CMake GUI.

Don't seem to have the path right. Have commented out this line

> before_build:
> #  - cd c:\project\climatology_pi

**Comment by nohal** [comment]
DELETE LINE 36, the one that says `  - cd ..`

**Comment by nohal** [comment]
You also have to fix line 35 which you have broken in https://github.com/seandepagnier/climatology_pi/pull/46/commits/a7798d04e43af2ee95d280b101a16170b89b4127

**Comment by rgleason** [comment]
Appveyor started to compile, but ended with 

> C:\project\climatology_pi\build\climatology_pi.vcxproj" (default target) (8) ->
> (Link target) -> 
>   zuFile.obj : error LNK2019: unresolved external symbol _gzopen referenced in function _zu_open [C:\project\climatology_pi\build\climatology_pi.vcxproj]
>   zuFile.obj : error LNK2019: unresolved external symbol _gzread referenced in function _zu_read [C:\project\climatology_pi\build\climatology_pi.vcxproj]
>   zuFile.obj : error LNK2019: unresolved external symbol _gzseek referenced in function _zu_rewind [C:\project\climatology_pi\build\climatology_pi.vcxproj]
>   zuFile.obj : error LNK2019: unresolved external symbol _gztell referenced in function _zu_rewind [C:\project\climatology_pi\build\climatology_pi.vcxproj]
>   zuFile.obj : error LNK2019: unresolved external symbol _gzclose referenced in function _zu_can_read_file [C:\project\climatology_pi\build\climatology_pi.vcxproj]
>   C:\project\climatology_pi\build\Release\climatology_pi.dll : fatal error LNK1120: 5 unresolved externals [C:\project\climatology_pi\build\climatology_pi.vcxproj]
>     7 Warning(s)
>     6 Error(s)
> 

I will look at line 35, I see , I need that line and need to remove the 'comment-out'.

**Comment by nohal** [comment]
Yes, that will not fix the Windows build, but you will be done with Appveyor

**Comment by rgleason** [comment]
I think there are cmakelists.txt changes needed for bzip.lib etc.

**Comment by rgleason** [comment]
Result;
These look like they are related to zlib

> C:\project\climatology_pi\build\climatology_pi.vcxproj" (default target) (8) ->
> (Link target) ->
> zuFile.obj : error LNK2019: unresolved external symbol _gzopen referenced in function _zu_open [C:\project\climatology_pi\build\climatology_pi.vcxproj]
> zuFile.obj : error LNK2019: unresolved external symbol _gzread referenced in function _zu_read [C:\project\climatology_pi\build\climatology_pi.vcxproj]
> zuFile.obj : error LNK2019: unresolved external symbol _gzseek referenced in function _zu_rewind [C:\project\climatology_pi\build\climatology_pi.vcxproj]
> zuFile.obj : error LNK2019: unresolved external symbol _gztell referenced in function _zu_rewind [C:\project\climatology_pi\build\climatology_pi.vcxproj]
> zuFile.obj : error LNK2019: unresolved external symbol _gzclose referenced in function _zu_can_read_file [C:\project\climatology_pi\build\climatology_pi.vcxproj]
> C:\project\climatology_pi\build\Release\climatology_pi.dll : fatal error LNK1120: 5 unresolved externals [C:\project\climatology_pi\build\climatology_pi.vcxproj]
> 7 Warning(s)
> 6 Error(s)

**Comment by rgleason** [comment]
Looking at weather_route_pi  commits
Windows Wx 3.1.2 zlib  #111
https://github.com/seandepagnier/weather_routing_pi/commit/cebcd1ab1fa7584672b5837d40e3895628cfaa80

The top has some changes from zlib to bzip in cmakelists.txt

**Comment by rgleason** [comment]
Pavel, do I need these conditional statements to get it working?
https://github.com/OpenCPN/OpenCPN/commit/1c283b81b6d493c90a792189bf183e992dd1c82f#diff-6dc4e9add31deb23a8ea9fdac6c033f0
lines 215 to 221?
> IF(WIN32)
>   IF(MSVC)
>     SET(OPENCPN_IMPORT_LIB "../../${CMAKE_CFG_INTDIR}/${PARENT}")
>     TARGET_LINK_LIBRARIES(${PACKAGE_NAME} "${CMAKE_SOURCE_DIR}/buildwin/zlib1.lib")
>   ELSE(MSVC)
>     SET(OPENCPN_IMPORT_LIB "${PARENT}.dll")
>     SET( CMAKE_SHARED_LINKER_FLAGS "-L../../" )

**Comment by rgleason** [comment]
Have added
#    INCLUDE_DIRECTORIES(${PLUGIN_SOURCE_DIR}/src/zlib-1.2.3)
    INCLUDE_DIRECTORIES(${CMAKE_SOURCE_DIR}/buildwin/include)

**Comment by nohal** [comment]
Just push your changes, do not copy them again to the text, that is useless...

**Comment by rgleason** [comment]
In weather_routing_pi  Hakan found he had to copy some zlib files into buildwin.
[Build in Win against O 4.99 failed. #231](https://github.com/seandepagnier/weather_routing_pi/issues/231)

Will continue as you suggest above.

**Comment by nohal** [comment]
Simply copy those 3 lines, nothing needs to be added anywhere as it already is in the bundle...

**Comment by rgleason** [comment]
Have the same 6 linker errors, and I don't see all of the 3 lines that are needed. It has from Line44    TARGET_LINK_LIBRARIES( ${PACKAGE_NAME} LIB_BZIP )
    INCLUDE_DIRECTORIES(${CMAKE_SOURCE_DIR}/buildwin/include)
    INCLUDE_DIRECTORIES(${PLUGIN_SOURCE_DIR}/src/bzip2)
ENDIF(NOT UNIX)

What are the other two lines that are missing?

**Comment by nohal** [comment]
allow_build_against_the_buildwin_dependency_pack_for_wx3_1_and_vs2017 _ _opencpn_opencpn_1c283b8

**Comment by rgleason** [comment]
Thank you. Pavel. I will try to do this properly, later tonight. You are very patient with me. Thanks again.

**Comment by rgleason** [comment]
By some miracle it compiled successfully with no errors and 9 warnings. I tried the appveyor file [here](https://ci.appveyor.com/project/seandepagnier/climatology-pi/builds/22481701/artifacts) and it loads into ov4.99.1408 and can be enabled. The climatology icon shows in the menu and I can briefly select what month, but nothing is showing on the screen and there are some crashes.

**Comment by rgleason** [comment]
I am going to close this and clean it up, by making an ov50 branch and simplifying the changes, then make a better PR.
